language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls
script:
  - nosetests --nologcapture --with-coverage --cover-package=datapackage_registry --cover-inclusive --cover-erase --cover-tests
after_success:
  - coveralls
