language: python
python:
  - 3.5
sudo: false
env:
  fast_finish: true
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
install:
  - pip install tox coveralls
script: tox
