environment:
  matrix:
    - PYTHON: 'C:\\Python27'
    - PYTHON: 'C:\\Python33'
    - PYTHON: 'C:\\Python34'
    - PYTHON: 'C:\\Python35'

install:
  - '%PYTHON%\\python.exe -m pip install tox'

test_script:
  - '%PYTHON%\\scripts\\tox'
